load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("@rules_kotlin//kotlin:lint.bzl", "ktlint_fix", "ktlint_test")

kt_jvm_library(
    name = "kraken-client",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:kotlin_serialization",
        "//core",
        "//order-state",
        "@maven//:io_github_microutils_kotlin_logging_jvm",
        "@maven//:io_ktor_ktor_client_cio_jvm",
        "@maven//:io_ktor_ktor_client_content_negotiation_jvm",
        "@maven//:io_ktor_ktor_client_core_jvm",
        "@maven//:io_ktor_ktor_client_websockets_jvm",
        "@maven//:io_ktor_ktor_serialization_kotlinx_json_jvm",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm",
    ],
)

ktlint_test(
    name = "ktlint",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    config = "//:ktlint_config",
    tags = ["ktlint"],
)

ktlint_fix(
    name = "ktlint_fix",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    config = "//:ktlint_config",
)
